/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Bomberman Fantasy Race)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800C0AE4u
#define func_800C0AE4 BootEntry  /* alias */
